### ISSUE TITLE
Make less a peerDependency (and/or upgrade to 3.8.1)

### ISSUE THREAD

**Issue by matthew-dean** [ionic-team/stencil-less#1]
Ideally, `less` would be a peerDependency and installed by the local project. As it stands, this plugin is pinned to Less 3.0.1, and there were a lot of features released with Less 3.5, such as Maps: http://lesscss.org/features/#maps-feature

I wanted to use these to define theme vars like:
```less
// vars.less
@colors: {
  accent: rgba(32, 191, 85, 1);
  main: rgba(11, 79, 108, 1);
  main-light: rgba(1, 186, 239, 1);
  neutral-light: rgba(251, 251, 255, 1);
  neutral-dark: rgba(117, 117, 117, 1);
}

// app.less
header {
  background: @colors[main];
  // ...
}
```
This type of organization wasn't available pre Less 3.5 and IMO is essential for theming.
